services:
    mysql:
        image: mysql:8.4
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DATABASE_NAME}'
            MYSQL_USER: '${DATABASE_USER}'
            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'sp-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sp
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DATABASE_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sp:
        driver: bridge
volumes:
    sp-mysql:
        driver: local
